/**
 * Generate supabase/seed.sql from the TypeScript seed exercise library so
 * the app bundle and the database never drift.
 *
 * Run: bun run scripts/generate-seed-sql.ts
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { SEED_EXERCISES } from '../src/data/seedExercises';

const q = (value: string): string => `'${value.replace(/'/g, "''")}'`;
const j = (value: unknown): string => `${q(JSON.stringify(value))}::jsonb`;

const rows = SEED_EXERCISES.map(
  (e) =>
    `(${[
      q(e.id),
      'null', // user_id: global seed row
      q(e.name),
      q(e.description),
      j(e.instructions),
      j(e.primaryMuscles),
      j(e.secondaryMuscles),
      j(e.equipment),
      q(e.difficulty),
      q(e.movementPattern),
      e.animationUrl ? q(e.animationUrl) : 'null',
      'false',
    ].join(', ')})`,
);

const sql = `-- Generated by scripts/generate-seed-sql.ts — do not edit by hand.
insert into public.exercises
  (id, user_id, name, description, instructions, primary_muscles,
   secondary_muscles, equipment, difficulty, movement_pattern,
   animation_url, is_custom)
values
${rows.join(',\n')}
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  instructions = excluded.instructions,
  primary_muscles = excluded.primary_muscles,
  secondary_muscles = excluded.secondary_muscles,
  equipment = excluded.equipment,
  difficulty = excluded.difficulty,
  movement_pattern = excluded.movement_pattern,
  animation_url = excluded.animation_url,
  updated_at = now()
where public.exercises.user_id is null;
`;

const outPath = join(import.meta.dir, '..', 'supabase', 'seed.sql');
writeFileSync(outPath, sql);
console.log(`Wrote ${SEED_EXERCISES.length} exercises to ${outPath}`);
